### ISSUE TITLE
A joke repo for a joke guy

### ISSUE THREAD

**Issue by tiliarou** [Banginpadr/mupen64plus-core#3]
## Expected Behavior
Not trying to steal other's work, appropriate code and impersonate other for greed.
## Current Behavior
Exactly the opposite of the above.
## Possible Solution (optional)
Stop all your stupid tentatives and just behave like a moral person (if you have any). Also stop your childish bot and fake accounts just for your personal gain when it's obvious that you offered nothing to contribute to this project.

**Comment by Banginpadr** [comment]
> ## Expected Behavior
> 
> Not trying to steal other's work, appropriate code and impersonate other for greed.
> ## Current Behavior
> 
> Exactly the opposite of the above.
> ## Possible Solution (optional)
> 
> Stop all your stupid tentatives and just behave like a moral person (if you have any). Also stop your childish bot and fake accounts just for your personal gain when it's obvious that you offered nothing to contribute to this project.
> ## mupen64plus-core configuration

wtf you are talking about you dumb motherfucker? what bots and what accounts?
